import type { Metadata } from "next";
import { Inter, Playfair_Display, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";

const interSans = Inter({
	variable: "--font-inter-sans",
	subsets: ["latin"],
});

const playfairDisplaySerif = Playfair_Display({
	variable: "--font-playfair-display-serif",
	subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
	variable: "--font-roboto-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${interSans.variable} ${playfairDisplaySerif.variable} ${robotoMono.variable} antialiased`}
				suppressHydrationWarning
			>
				<Providers>{children}</Providers>
				<Toaster
					position="bottom-right"
					richColors
					toastOptions={{
						className: "border-border bg-card text-card-foreground",
					}}
				/>
			</body>
		</html>
	);
}
